final String personalIntro = "I am a developer from outside New York City "
    "always looking to expand my toolbox. From competitive coding to "
    "large-scale projects with my previous companies and the small projects "
    "I do on the side to entertain myself, my experience as a developer has "
    "been a rollercoaster I refuse to get off. I strive to put my work into "
    "the hands of people across the planet, and usher new passengers aboard "
    "this wild ride.";
final String tvcsdText = "During my time in high school, I was able to take "
    "two years of Cisco Networking courses. At the end of my senior year, my "
    "teacher invited me and a friend to intern for the summer with the "
    "district's Information Technology department where I got to do some really"
    " fun, hands-on work with a super friendly team.";
final String yonseiText = "During the summer after my freshman year at "
    "Northeastern University, I was able to study abroad at Yonsei University"
    " in Seoul, South Korea. During my time there, I had the opportunity to "
    "work in the university's Center for Nano-Wear research lab. The lab "
    "specialized in tribology, or the study of friction and wear of materials,"
    " and was tasked with performing tests for both Samsung and Hyundai "
    "during my time with the lab. Personally, I worked on 3D modelling and "
    "printing adapters to expand the type of testing the lab could do and "
    "presented on underlying physics concepts of project proposals at weekly "
    "lab meetings.";
final String cantellaText = "My first coop was spent working with Cantella & "
    "Co. as a software developer working on a full-stack web app aimed at "
    "streamlining the everyday activities of financial advisors. The app used "
    "Docusign to support document e-delivery and distribution, and a mySQL "
    "database to track document status and support file sharing. My original "
    "position was extended through the rest of the summer, and then extended "
    "again through the following fall semester where I took on a lead "
    "designer role.";
final String morseText = "My second coop brought me to MORSE corp where I "
    "worked on evaluating performance of computer vision algorithms. During my "
    "time at MORSE, I released a Python package for generating metrics based "
    "algorithm results following a plug-in design architecture allowing for "
    "easy configuration and definition of new metrics. I also designed "
    "performant data pipelines using said tools that processed model data "
    "at the petabyte scale.";
final String wirelessText = "My humble beginning in machine learning. A simple "
    "TensorFlow model trained on custom features such as, 'percent english "
    "used' and 'title repetitions' to identify the artist of a korean pop song "
    "based on the lyrics. Our model had an accuracy of 70% with a train, test, "
    "validation pool of only around 100 songs. Our model was awarded the "
    "'Coolest Algorithm' award for the competition and a BB8 robot!";
final String mitText = "HackMIT 2019 was easily the largest hackathon I have "
    "been to. We had the idea of creating a website that can help combat "
    "the proliferation of fake news and partisan news bubbles by taking a "
    "provided article, scraping the text from the article, running it though "
    "Google Cloud's sentiment and keyword analysis to determine the topic and "
    "viewpoint. From here, we search the internet using Google's search API "
    "to find additional articles on the same topic and display then with their "
    "sentiments to the user. We were awarded first prize for 'Best Use of "
    "Google Cloud API'.";
final String codejamText = "Every year I look forward to testing my "
    "competitive programming chops with Google CodeJam and KickStart ever "
    "since my humble beginnings in the American Computer Science League in 10th"
    " grade. While my accolades are limited to two Round 1 finishes for "
    "CodeJam and a 1238th finish in KickStart, I look forward to honing my "
    "skills even further!";
final String focusText = "A pure for-fun project designed to combat my love "
    "for YouTube and Twitch.tv. Focus Lights, or more colloquially known as "
    "'Do Your Work, Idiot' is a chrome extension that allows the user to set a "
    "timer for which they want to concentrate and if they extension detects "
    "the user on any of a predefined blacklist of websites, it will send "
    "requests to the Philips Hue bulbs in the room to flash randomly until the "
    "tabs are closed.";
final String discordText = "Discord Swear Jar is another quirky project "
    "initially designed to use a predefined list of words and costs to send "
    "payments on Venmo to a designated recipient whenever one of the words is "
    "detected by a GSpeech client. While I was working on this project, "
    "Braintree Payments locked down their API to business partners so I was "
    "forced to pivot to using Twilio to notify the intended recipient.";
final String obstacleText = "At Northeastern I was a founding member and now "
    "vice president of Elite Heat, the Obstacle Course Racing Club on campus. "
    "I'm a member of the 2019 Spartan Trifecta Tribe having completed a "
    "Spartan Sprint, Super, and Beast during the calendar year. I've also ran "
    "2 Rugged Maniacs, 2 Blizzard Blasts, and the Navy Seals' Bonefrog. The "
    "2020 Season was cut short but I really wanna tackle some races outside "
    "the Northeast.";
final String boulderText = "Through casual bouldering events with Elite Heat, "
    "I learned that the terrifying activity of middle school birthday parties "
    "was far more fun than I remembered. I began bouldering regularly in "
    "September of 2019 at RockSpot in South Boston and it was quickly become "
    "my favorite means of staying active. I currently climb at a V3 level and "
    "have my eyes set at tougher grades.";
final String filmText = "The process of making films has always interested me. "
    "While I am still very much a novice, I enjoy experimenting with all "
    "stages of video production in both my production classes at Northeastern, "
    "pursuing my minor in Film Production and personal video projects "
    "surrounding my technical work and other hobbies. I'd love to continue to "
    "document, entertain, and inform people about all the things that "
    "fascinate me in the future.";
final String esportText = "I've been playing video games as long as I can "
    "remember and I credit them for the competitiveness and analytical nature "
    "to most things I do. The game that's had the longest lasting impact on me "
    "has been Dota 2, which I've been playing for around 8 years and fall "
    "between the top 1 to 2 percent of players. The field of esports in "
    "general interests me as I'm excited to see it gain more of the mainstream "
    "notoriety it deserves.";
